version: "3.13"
services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: 1256
      POSTGRES_USER: postgres
      POSTGRES_DB: project
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}", "-d", "${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    container_name: app
    env_file:
      - .env
    ports:
      - 8001:8001
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/app/entrypoint.sh"]